//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolineas.DataStorage.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AerolineasEntities : DbContext
    {
        public AerolineasEntities()
            : base("name=AerolineasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Itinerario> Itinerario { get; set; }
    
        public virtual ObjectResult<Itinerarios> ObtenerItinerario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Itinerarios>("ObtenerItinerario");
        }
    }
}
