//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolineas.DataStorage.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario
    {
        public int Id { get; set; }
        public Nullable<int> IdAvion { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<decimal> HorasVuelo { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Ciudad Ciudad { get; set; }
    }
}
